name: bookly
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  go_router: ^14.2.7
  flutter_native_splash: ^2.4.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^5.7.0
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#100b20"
  image: "assets/images/books.png"
  android_12:
    color: "#100b20"
    image: "assets/images/books.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf
